### ISSUE TITLE
[Bug] Mod crashes on startup

### ISSUE THREAD

**Issue by Easyidle123** [TheMisterFish/Fabric_TwinSession#4] opened 2024-10-11 20:22 UTC
**Describe the bug**
_The mod crashes when attempting to start the game_

**To Reproduce**
_Steps to reproduce the behavior:_
1. Using prism launcher, create a new Fabric 1.21.1 instance
2. In the instance, download Fabric API 0.105.0 & TwinSession 1.0.1
3. Launch the game

**Expected behavior**
_The game boots properly._

**Versions (please complete the following information):**
- Minecraft: 1.21.1
- Fabric Loader: 0.16.7
- Mod Version: 1.0.1

**Additional context**
_[Crash Log](https://mclo.gs/bTNGZYu)._

**Comment by TheMisterFish** [comment] 2024-10-12 14:20
I'm not able to reproduce the error but I think it's because of the random-generator I was using. Instead of using the java version, I've changed it so it used the minecraft build-in random generator. Will be available in release 1.0.2; I'll update you when it's released.

**Comment by TheMisterFish** [comment] 2024-10-12 14:33
@Easyidle123 could you try out [Version 1.0.2](https://github.com/TheMisterFish/Fabric_TwinSession/releases/tag/v1.0.2-mc.1.21.1)?

If it works I'll close this issue :)

**Comment by Easyidle123** [comment] 2024-10-14 19:36
Confirmed Fixed!

**Comment by Easyidle123** [comment] 2024-10-14 19:36
@TheMisterFish Confirmed fixed!

**Closed** 2024-10-14 19:37 UTC
Labels: bug
